backend:
  name: github
  repo: Pedrobatista2024/Perfumaria
  branch: main
  publish_mode: editorial_workflow
  client_id: Ov23lijtRItTv10LcGSd

media_folder: "assets/images"
public_folder: "assets/images"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "_data"
    create: true
    slug: "{{nome}}"
    fields:
      - {label: "Nome", name: "nome", widget: "string", required: true}
      - {label: "Gênero", name: "genero", widget: "select", options: ["Masculino", "Feminino"]}
      - {label: "Fragrância", name: "fragrancia", widget: "string"}
      - {label: "Descrição", name: "descricao", widget: "text"}
      - {label: "Preço", name: "preco", widget: "string"}
      - {label: "Imagem", name: "imagem", widget: "image"}
      - {label: "URL WhatsApp", name: "url_wpp", widget: "string", hint: "O link completo do WhatsApp para compra."}